duha-dubeoghaukka/duha-frontend

- src/components/signin/SignUpForm.jsx
- src/index.css
- src/pages/user/SignUp.jsx
- src/shared/Router.js
- tailwind.config.js
버튼 컴포넌트 설정 : btn-primary 기본 버튼 /  btn-white 하얀색 버튼
컬러 설정 : 적용방법 bg-green1 => 배경 초록색
> Feat:tailwind css setting

- .eslintrc
- yarn.lock
> [Fix] prettier 설정 수정

- src/components/schedule/ScheduleCard.jsx
> Fix: variable name 수정

- src/api/api.js
- api 폴더에서 axios interceptors 위치 상단으로 변경
> Fix: axios interceptors 위치 변경

- src/components/layout/Layout.jsx
- src/components/mainpage/HomeCard.jsx
- src/pages/mainpage/MainPage.jsx
- layout 컴포넌트에 home 추가
- mainpage 기본 ui 구현 완료
> Feat: 메인페이지(홈) 추가 및 ui 적용

- .eslintrc
- src/components/mypage/FavoriteItemList.jsx
- src/pages/mypage/FavoritesListPage.jsx
- src/shared/Router.js
- 즐겨찾기 목록 UI 구현 완료
- 각 즐겨찾기 목록 별 개수 api 연동 필요 (api 구현 완료되는대로 구현 예정)
- 즐겨찾기한 일정, 관광, 맛집 routing 처리 필요 (즐겨찾기 기능 완료되는대로 구현 예정)
> Feat: [마이페이지] 즐겨찾기 목록 UI 구현 완료

- src/api/api.js
- src/components/schedule/ShareCard.jsx
- src/pages/schedule/ShareSchedulePage.jsx
- src/shared/Router.js
- 일정 공유 조회 api 연동
- 각 일정 별 routing 연결 필요
> Feat: 일정 공유 조회 

- .eslintrc
- src/components/layout/Layout.jsx
- 일정 공유 routing 연결
- eslint parser 주석 처리
> Fix : 일정 공유 routing 등록

- src/api/api.js
- src/components/schedule/ScheduleCard.jsx
> Feat: 일정 삭제 api 추가 및 연동

- src/api/api.js
- src/components/schedule/ScheduleCard.jsx
> Fix: 해결 ->  일정 삭제 시 코스 조회되는 문제

- src/components/schedule/Registration.jsx
- src/pages/mypage/FavoritesListPage.jsx
- src/pages/schedule/ScheduleRegisterPage.jsx
- src/pages/schedule/ShareSchedulePage.jsx
- src/utils/routingLoginPage.js
- 비회원 로그인으로 이동시키는 함수 생성
- 함수 재사용해서 일정 등록, 일정 공유, 마이페이지 비회원 접근시 로그인 페이지로 이동
> Fix: 일정 공유, 등록, 마이페이지 비회원 -> 로그인으로 이동 처리

- src/components/layout/Layout.jsx
- src/pages/mypage/FavoriteAccommodationPage.jsx
- src/pages/mypage/FavoriteRestaurantsPage.jsx
- src/pages/mypage/FavoriteSpotsPage.jsx
- src/pages/mypage/FavoritesListPage.jsx
- src/utils/decodeToken.js
> Feat: 닉네임 기능 추가

- src/api/api.js
- src/components/schedule/ShareCard.jsx
- src/components/schedule/ShareDetail.jsx
- src/pages/schedule/ShareDetailPage.jsx
- src/shared/Router.js
- 일정 id 별로 사용자들이 공유 설정한 상세 코스 조회 추가
- day 별로 코스가 있을 경우, 없을 경우 데이터 처리
> Feat: 일정 공유 - 코스 조회 기능 추가

- src/components/schedule/ShareDetail.jsx
> Fix: 일정 공유 - 코스 조회 지도 추가

- src/api/api.js
- src/components/mypage/TripItem.jsx
- src/pages/mypage/FavoriteAccommodationPage.jsx
- src/pages/mypage/FavoriteCoursePage.jsx
- src/pages/mypage/FavoriteRestaurantsPage.jsx
- 마이페이지 일정 즐겨찾기 기능 추가
- 일정 즐겨찾기 확인 및 코스 조회 가능
- 마이페이지 일정 즐겨찾기 카드 컴포넌트 추가
- 마이페이지 맛집, 숙소 즐겨찾기 관련 text 수정
> Feat: 마이페이지 -> 즐겨찾기 text 수정 및 일정 즐겨찾기 추가

- src/api/api.js
- src/utils/decodeToken.js
- 로그인 플랫폼별 닉네임 처리
- 로그인 플랫폼마다 닉네임이 중복처리될 가능성이 있어서 예)kakao_nickName 이런식으로 처리
- 일반 로그인의 경우 nickName으로만 처리
> Feat: 로그인 플랫폼별 닉네임 처리

- .eslintrc
- src/components/mainpage/HomeCard.jsx
- src/components/mypage/FavoriteItemList.jsx
- 카드를 눌렀을 때 routing 처리
- [메인페이지 - 홈] 적용
- [마이페이지 - 즐겨찾기 목록] 적용
> Fix: 화살표 아닌 카드 누를 때 routing 처리

- src/api/api.js
- src/components/editInfo/EditUserInfoForm.jsx
- src/components/schedule/ScheduleCard.jsx
- src/index.js
- src/pages/schedule/ScheduleRegisterPage.jsx
- src/redux/config/configStore.js
- src/redux/modules/schedules.js
- 삭제 시 window.location.reload() 대신 redux thunk 사용 일정 조회 및 삭제 redux로 상태 관리
> Fix: 일정 삭제 시 렌더링 이슈 해결

- .eslintrc
- src/components/schedule/Registration.jsx
- src/components/schedule/ScheduleCard.jsx
- src/redux/modules/schedules.js
- src/shared/Router.js
- 일정 수정 기능 구현
- 달력에 기존 일정 range로 표시하는 기능은 찾아보는 중
> Feat: 일정 수정 

- .eslintrc
- package.json
- src/components/modal/Modal.jsx
- src/components/modal/ShowModal.jsx
- src/components/schedule/DayItem.jsx
- src/components/schedule/ScheduleCard.jsx
- src/components/shareLink/ShareLink.jsx
- src/hooks/useChange.js
- src/pages/schedule/AddCourse.jsx
- src/utils/shareKakaoLink.js
- tailwind.config.js
- yarn.lock
- 일정 공유 링크 기능 추가
- 카카오, 링크 복사 기능 추가
- url 이슈 해결 #95
> Feat: 일정 공유 링크 기능 추가

- src/api/api.js
- src/components/schedule/ScheduleCard.jsx
- 링크 공유에 ```e.stopPropagation();``` 적용시 전체 카드가 눌려서 코스 추가 페이지로 이동하는 이슈 발생 -> css 재수정
> Fix: 스케줄 카드 css 수정

- .eslintrc
- src/components/card/Card.jsx
- src/components/mainpage/HomeCard.jsx
- src/components/mypage/FavoriteItemList.jsx
- src/pages/mypage/FavoritesListPage.jsx
- 모바일로 홈, 즐겨찾기 목록 조회시 마지막 카드가 잘려서 보임 -> h-full로 해결
- 마이페이지-즐겨찾기 조회시 모바일은 md:text-sm으로 조정
> Fix: 홈, 즐겨찾기 목록 h-screen -> h-full, text 크기 조정

- src/api/api.js
- src/components/login/LogInForm.jsx
- src/components/modal/InputEmail.jsx
- src/components/signin/SignUpForm.jsx
- src/utils/getCode.js
- getCode 함수 추가 : 쿼리 스트링 형태로 전달되는 code 받아오기 위한 함수
- 이메일 인증 모달 추가
- 회원가입 폼으로 넘어갈 때 인증된 이메일 디폴트 값으로 처리
> Feat: 이메일 인증 기능 추가

- src/components/modal/InputEmail.jsx
- 이메일 인증시 모바일에서 alert창이 잘 안뜸
- alert창 대신 input 태그 밑에 <p> 태그 추가해서 message 형태로 보이도록 변경
- 이메일 입력시 아무것도 입력하지 않았을 경우 "이메일을 입력하세요" 처리
> Fix: 이메일 인증 이슈 처리

- src/pages/menu/MypageInfo.jsx
- src/pages/menu/ScheduleInfo.jsx
> Fix: 일정, 마이페이지 로그인 여부 확인

- src/components/schedule/DayItem.jsx
- 메인에 머지하고 충돌을 해결하는 과정에서 다시 변경 전 상태로 돌아간 것 같음
> Fix: Dayitem에서 id값 useParams로 변경

- src/components/card/Card.jsx
- src/components/mainpage/HomeCard.jsx
- src/index.css
> Design: 메인페이지 css 수정
